<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $course->code }} Study Handout</title>
    <style>
        body { font-family: 'Helvetica', sans-serif; color: #333; line-height: 1.6; }
        .header { text-align: center; border-bottom: 2px solid #2563eb; padding-bottom: 20px; margin-bottom: 30px; }
        .header h1 { color: #1e40af; margin: 0; font-size: 24px; }
        .header p { color: #64748b; margin: 5px 0 0; font-size: 14px; }
        .week-container { margin-bottom: 40px; page-break-inside: avoid; }
        .week-title { background: #eff6ff; color: #1e40af; padding: 10px 15px; font-weight: bold; font-size: 18px; border-left: 4px solid #2563eb; }
        .week-summary { margin: 10px 0; font-style: italic; color: #475569; font-size: 13px; }
        .day-grid { margin-top: 15px; border: 1px solid #e2e8f0; border-collapse: collapse; width: 100%; }
        .day-grid th, .day-grid td { border: 1px solid #e2e8f0; padding: 12px; text-align: left; vertical-align: top; }
        .day-grid th { background: #f8fafc; color: #475569; font-size: 12px; text-transform: uppercase; width: 25%; }
        .day-grid td { font-size: 13px; }
        .tasks { margin-top: 15px; }
        .tasks h4 { font-size: 12px; text-transform: uppercase; color: #94a3b8; margin-bottom: 5px; }
        .tasks ul { margin: 0; padding-left: 20px; }
        .tasks li { font-size: 12px; color: #475569; }
        .footer { text-align: center; font-size: 10px; color: #94a3b8; margin-top: 50px; border-top: 1px solid #e2e8f0; padding-top: 20px; }
    </style>
</head>
<body>
    <div className="header">
        <h1>Study Handout: {{ $course->title }}</h1>
        <p>{{ $course->code }} | Personalized Study Strategy for {{ $user->name }}</p>
    </div>

    @foreach($readingPlan as $weekKey => $weekData)
        <div className="week-container">
            <div className="week-title">Week {{ str_replace('week_', '', $weekKey) }} Breakdown</div>
            <p className="week-summary">{{ $weekData['summary'] }}</p>

            <table className="day-grid">
                <thead>
                    <tr>
                        <th>Day</th>
                        <th>Content to Master</th>
                    </tr>
                </thead>
                <tbody>
                    @if(isset($weekData['daily_segments']) && count($weekData['daily_segments']) > 0)
                        @foreach($weekData['daily_segments'] as $day => $content)
                            <tr>
                                <td><strong>{{ $day }}</strong></td>
                                <td>{{ $content }}</td>
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td><strong>General</strong></td>
                            <td>Consolidate week's topics and review past materials.</td>
                        </tr>
                    @endif
                </tbody>
            </table>

            <div className="tasks">
                <h4>Weekly Action Tasks</h4>
                <ul>
                    @foreach($weekData['tasks'] as $task)
                        <li>{{ $task }}</li>
                    @endforeach
                </ul>
            </div>
        </div>
    @endforeach

    <div className="footer">
        Generated by Phronix AI - Your Academic Strategic Partner<br>
        Date: {{ date('F j, Y') }}
    </div>
</body>
</html>
